//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elin.Plugin.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elin.Plugin.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot apply attribute to a nested type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG001_A_Title {
            get {
                return ResourceManager.GetString("EPG001_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is a nested type. Because attribute &apos;{1}&apos; cannot be applied to nested types. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG001_B_Message {
            get {
                return ResourceManager.GetString("EPG001_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual is not allowed on properties of class types に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG002_A_Title {
            get {
                return ResourceManager.GetString("EPG002_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property &apos;{1}&apos; of {0} is marked as virtual. Due to constraints of the generated internal code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG002_B_Message {
            get {
                return ResourceManager.GetString("EPG002_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unsupported type is used as a setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG003_A_Title {
            get {
                return ResourceManager.GetString("EPG003_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property &apos;{1}&apos; of {0} has a type ({2}) that cannot be used as settings data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG003_B_Message {
            get {
                return ResourceManager.GetString("EPG003_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element type does not match the declared type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG004_A_Title {
            get {
                return ResourceManager.GetString("EPG004_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot specify &apos;{1}&apos; as the range value for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG004_B_Message {
            get {
                return ResourceManager.GetString("EPG004_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Named arguments are not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG005_A_Title {
            get {
                return ResourceManager.GetString("EPG005_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must call the method using named arguments. Due to limitations of the definition file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG005_B_Message {
            get {
                return ResourceManager.GetString("EPG005_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters are not used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG006_A_Title {
            get {
                return ResourceManager.GetString("EPG006_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] &apos;{1}&apos; does not use any parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG006_B_Message {
            get {
                return ResourceManager.GetString("EPG006_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parameter definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG007_A_Title {
            get {
                return ResourceManager.GetString("EPG007_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] No parameters are defined for &apos;{1}&apos;. You must define {1}.parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG007_B_Message {
            get {
                return ResourceManager.GetString("EPG007_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter count does not match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG008_A_Title {
            get {
                return ResourceManager.GetString("EPG008_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] The number of parameters in the &apos;{1}&apos; message ({2}) does not match the number of properties in {1}.parameters ({3}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG008_B_Message {
            get {
                return ResourceManager.GetString("EPG008_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters are not defined に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG009_A_Title {
            get {
                return ResourceManager.GetString("EPG009_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] The parameter &apos;{2}&apos; in the &apos;{1}&apos; message must be defined as {1}.parameters.{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG009_B_Message {
            get {
                return ResourceManager.GetString("EPG009_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters do not match the base language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG010_A_Title {
            get {
                return ResourceManager.GetString("EPG010_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] The message parameter &apos;{2}&apos; in the base language for &apos;{1}&apos; must also be included for language &apos;{3}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG010_B_Message {
            get {
                return ResourceManager.GetString("EPG010_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assembly name is not configured に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG011_A_Title {
            get {
                return ResourceManager.GetString("EPG011_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the assembly name in Directory.Build.props.user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG011_B_Message {
            get {
                return ResourceManager.GetString("EPG011_B_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG012_A_Title {
            get {
                return ResourceManager.GetString("EPG012_A_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPG012_B_Message {
            get {
                return ResourceManager.GetString("EPG012_B_Message", resourceCulture);
            }
        }
    }
}
