using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Elin.Plugin.Generator
{
    public class SourceBuilder
    {
        public SourceBuilder()
        {
            Xml = new XmlDocumentCommentBuilder(this);
        }

        #region property

        public string Header { get; } = "// <auto-generated/>";
        public string EmptyStringLiteral => ToStringLiteral(string.Empty);

        public XmlDocumentCommentBuilder Xml { get; }

        #endregion

        #region function

        public bool IsIgnoreAttribute(INamedTypeSymbol attributeClass)
        {
            var attributeName = attributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (attributeName is null)
            {
                return true;
            }

            var compilerAttributes = new[] {
                "global::System.Runtime.CompilerServices.NullableContextAttribute",
                "global::System.Runtime.CompilerServices.NullableAttribute",
                "global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute",
            };

            return !compilerAttributes.Contains(attributeName, StringComparer.Ordinal);
        }

        public IEnumerable<AttributeData> FilterAttribute(IEnumerable<AttributeData> attributes)
        {
            foreach (var attributeData in attributes)
            {
                var attributeClass = attributeData.AttributeClass;
                if (attributeClass is null)
                {
                    continue;
                }
                if (!IsIgnoreAttribute(attributeClass))
                {
                    continue;
                }

                yield return attributeData;
            }
        }

        public string ToCode<T>(T target)
            where T : Enum
        {
            var type = target.GetType();
            return "global::" + type.FullName + "." + target.ToString();
        }

#pragma warning disable CS1591 // 公開されている型またはメンバーの XML コメントがありません
        public string ToCode<T>()
#pragma warning restore CS1591 // 公開されている型またはメンバーの XML コメントがありません
        {
            var type = typeof(T);
            return "global::" + type.FullName;
        }

        public string ToCode(Accessibility accessibility)
        {
            return accessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.ProtectedAndInternal => "private protected",
                Accessibility.Private => "private",
                _ => throw new NotSupportedException($"accessibility: {accessibility}"),
            };
        }

        public string ToCode(TypedConstant c)
        {
            if (c.IsNull)
            {
                return "null";
            }

            switch (c.Kind)
            {
                case TypedConstantKind.Primitive:
                    {
                        switch (c.Value)
                        {
                            case string s:
                                return ToStringLiteral(s);
                            case bool b:
                                return b ? "true" : "false";
                            case char ch:
                                return ToCharLiteral(ch);
                            default:
                                return Convert.ToString(c.Value, System.Globalization.CultureInfo.InvariantCulture);
                        }
                    }

                case TypedConstantKind.Enum:
                    {
                        if (c.Type is null)
                        {
                            throw new InvalidOperationException("Enum type is null");
                        }
                        if (c.Value is null)
                        {
                            throw new InvalidOperationException("Enum value is null");
                        }
                        var enumType = c.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        var enumFields = c.Type.GetMembers().OfType<IFieldSymbol>();
                        var enumName = enumFields.First(a => c.Value.Equals(a.ConstantValue));
                        return enumType + "." + enumName.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    }

                case TypedConstantKind.Type:
                    if (c.Value is ITypeSymbol ts)
                    {
                        return "typeof(" + ts.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")";
                    }
                    break;
            }

            // 分かっている範囲で動けばいいので不明点は例外として、必要になったら対応する
            throw new NotSupportedException($"TypedConstant: {c.Kind} / Value: {c.Value}");
        }

        public string ToNamespaceCode(ISymbol symbol)
        {
            return symbol.ContainingNamespace.IsGlobalNamespace ?
                "// no namespace" :
                "namespace " + symbol.ContainingNamespace + ";"
            ;
        }

        public string ToSourceFilePath(ISymbol symbol)
        {
            var targetName = symbol.Name;
            var fullName = (symbol.ContainingNamespace.IsGlobalNamespace ? "" : symbol.ContainingNamespace + ".") + targetName;
            return $"{fullName}.g.cs";
        }

        private string ToCharactersLiteral(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t");
        }

        public string ToCharLiteral(char value)
        {
            return "'" + ToCharactersLiteral(value.ToString()) + "'";
        }

        public string ToStringLiteral(string value)
        {
            return "\"" + ToCharactersLiteral(value) + "\"";
        }

        protected internal virtual IEnumerable<string> SplitLines(string s)
        {
            using var reader = new StringReader(s);
            string? line;
            while ((line = reader.ReadLine()) != null)
            {
                yield return line;
            }
        }

        /// <summary>
        /// 行の編集。
        /// </summary>
        /// <param name="line">編集対象の行（改行を含まない単一行）。</param>
        /// <param name="prefix">行の先頭に追加する文字列。</param>
        /// <param name="suffix">行の末尾に追加する文字列。</param>
        /// <returns>プレフィックスとサフィックスを結合した編集後の行文字列。</returns>
        protected internal virtual string EditLine(string line, string prefix, string suffix)
        {
            return prefix + line + suffix;
        }

        public virtual IEnumerable<string> ApplyIndentLines(string indent, IEnumerable<string> lines)
        {
            return lines.Select(a => EditLine(a, indent, string.Empty));
        }

        public virtual string JoinLines(IEnumerable<string> lines)
        {
            return string.Join(Environment.NewLine, lines);
        }

        public string ApplyIndent(string indent, IEnumerable<string> lines)
        {
            return JoinLines(
                ApplyIndentLines(indent, lines)
            );
        }

        public string ApplyIndent(string indent, string source)
        {
            return ApplyIndent(
                indent,
                SplitLines(source)
            );
        }

        public string ApplyXmlDocumentComment(string indent, string xml)
        {
            var comments = Xml.ToDocumentComments(xml);
            return ApplyIndent(indent, comments);
        }

        public string Format(string code)
        {
            //var tree = CSharpSyntaxTree.ParseText(code);

            //var root = tree.GetRoot().NormalizeWhitespace();

            //var formattedCode = root.ToFullString();

            //return formattedCode;
            return code;
        }

        public Location GetLocation(ISymbol symbol)
        {
            return symbol.Locations.Length > 0 ? symbol.Locations[0] : Location.None;
        }

        #endregion
    }

    [Obsolete("XML ドキュメントコメントの手書きの限界が来た時に実装する予定")]
    public class XmlDocumentElement
    {
        public XmlDocumentElement(string elementName)
        {
            ElementName = elementName;
        }

        #region property

        public string ElementName { get; }
        public Dictionary<string, string> Attributes { get; } = new Dictionary<string, string>();

        #endregion
    }

    public class XmlDocumentCommentBuilder
    {
        public XmlDocumentCommentBuilder(SourceBuilder sourceBuilder)
        {
            SourceBuilder = sourceBuilder;
        }

        #region property

        private SourceBuilder SourceBuilder { get; }

        #endregion

        #region function

        public virtual string ToDocumentComment(string s)
        {
            return SourceBuilder.EditLine(s, "/// ", string.Empty);
        }

        /// <summary>
        /// 行一覧を XML ドキュメントコメント形式に変換する。
        /// </summary>
        /// <param name="lines"></param>
        /// <returns></returns>
        public virtual IEnumerable<string> ToDocumentComments(IEnumerable<string> lines)
        {
            return lines.Select(a => ToDocumentComment(a));
        }

        /// <summary>
        /// 文字列を XML ドキュメントコメント形式に変換する。
        /// </summary>
        /// <param name="xml"></param>
        /// <returns></returns>
        public IEnumerable<string> ToDocumentComments(string xml)
        {
            return ToDocumentComments(SourceBuilder.SplitLines(xml));
        }

        #endregion
    }
}
