name: Mod Template

on:
  push:
  workflow_dispatch:

jobs:

  initialize:
    name: Initialize

    runs-on: &mod-os-image windows-latest

    strategy:
      matrix:
        configuration: &matrix-configurations
          - Debug
          - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize
        shell: pwsh
        # バッチ叩くと死ぬので PowerShell で直接叩く(死ぬのは既知)
        run: |
          dev-items\initialize.ps1 -ModName "Initialize"

      - name: Artifact [initialize]
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v7
        with:
          name: initialize
          path: .

      - name: Checkout CI Module
        uses: actions/checkout@v6
        with: &checkout-ci-module
            repository: sk-0520/elin-mod-ci-infrastructure
            path: elin-mod-ci-infrastructure

      - name: Setup CI Module
        shell: pwsh
        run: |
          # .targets
          $targetsPath = "Directory.Build.targets.user"
          $targetsXml = [xml](Get-Content -Path $targetsPath -Encoding UTF8)

          $propertyGroup = $targetsXml.CreateElement("PropertyGroup")
          $steamPathGroup = $targetsXml.CreateElement("SteamPath")
          $steamPathGroup.InnerText = "${{ github.workspace }}"
          $elinPathGroup = $targetsXml.CreateElement("ElinPath")
          $elinPathGroup.InnerText = '$(SteamPath)\elin-mod-ci-infrastructure\libs'
          $modPathGroup = $targetsXml.CreateElement("ModPath")
          $modPathGroup.InnerText = "${{ github.workspace }}\output"

          $propertyGroup.AppendChild($steamPathGroup)
          $propertyGroup.AppendChild($elinPathGroup)
          $propertyGroup.AppendChild($modPathGroup)

          $targetsXml.Project.AppendChild($propertyGroup)

          $targetsXml.Save($targetsPath)

          Get-Content -Path $targetsPath -Encoding UTF8

      - name: Build
        shell: pwsh
        run: |
          dotnet build --configuration ${{ matrix.configuration }}

      - name: Artifact [build]
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: output

      - name: Build
        shell: pwsh
        run: |
          dotnet test --configuration ${{ matrix.configuration }}

  debug-dll:
    name: "Debug DLL"

    runs-on: *mod-os-image

    steps:
      - name: Checkout Mod
        uses: actions/checkout@v6

      - name: Prepare DLL
        id: dll
        shell: pwsh
        run: |
          $elinPath = Join-Path -Path "${{ github.workspace }}" -ChildPath "work-elin"
          $dllDirPath = Join-Path -Path $elinPath -ChildPath "MonoBleedingEdge" | Join-Path -ChildPath "EmbedRuntime"
          $dllName = "mono-2.0-bdwgc.dll"
          $dllPath = Join-Path -Path $dllDirPath -ChildPath $dllName
          New-Item -Path $dllPath -ItemType File -Force

          "DLL_DIR_PATH=$dllDirPath" >> $env:GITHUB_ENV
          "DLL_NAME=$dllName" >> $env:GITHUB_ENV
          "DLL_PATH=$dllPath" >> $env:GITHUB_ENV

      - name: Prepare DLL
        shell: pwsh
        run: |
          "DLL_DIR_PATH: ${{ steps.dll.outputs.DLL_DIR_PATH }}"
          "DLL_NAME: ${{ steps.dll.outputs.DLL_NAME }}"
          "DLL_PATH: ${{ steps.dll.outputs.DLL_PATH }}"
          "DLL_DIR_PATH: $env:DLL_DIR_PATH
          "DLL_NAME: $env:DLL_NAME
          "DLL_PATH: $env:DLL_PATH
