name: Mod Template

on:
  push:
  workflow_dispatch:

jobs:

  initialize:
    name: Initialize

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize
        shell: pwsh
        # バッチ叩くと死ぬので PowerShell で直接叩く(死ぬのは既知)
        run: |
          dev-items\initialize.ps1 -ModName "Initialize"

      - name: Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Initialize
          path: .
